export const DISTRICTS = [
  {
    id: 1001,
    regionId: 10,
    name_uz: 'UCHTEPA TUMANI',
    name_ru: 'УЧТЕПА ТУМАНИ',
    name_en: 'UCHTEPA DISTRICT',
  },
  {
    id: 1003,
    regionId: 10,
    name_uz: "MIRZO ULUG'BEK TUMANI",
    name_ru: 'МИРЗО УЛУҒБЕК ТУМАНИ',
    name_en: 'MIRZO ULUGBEK DISTRICT',
  },
  {
    id: 1005,
    regionId: 10,
    name_uz: 'YAKKASAROY TUMANI',
    name_ru: 'ЯККАСАРОЙ ТУМАНИ',
    name_en: 'YAKKASAROY DISTRICT',
  },
  {
    id: 1006,
    regionId: 10,
    name_uz: 'SHAYXONTOXUR TUMANI',
    name_ru: 'ШАЙХОНТОХУР ТУМАНИ',
    name_en: 'SHAYKHANTAKHUR DISTRICT',
  },
  {
    id: 1007,
    regionId: 10,
    name_uz: 'CHILONZOR TUMANI',
    name_ru: 'ЧИЛОНЗОР ТУМАНИ',
    name_en: 'CHILONZOR DISTRICT',
  },
  {
    id: 1008,
    regionId: 10,
    name_uz: "SIRG'ALI TUMANI",
    name_ru: 'СИРҒАЛИ ТУМАНИ',
    name_en: 'SIRGALI DISTRICT',
  },
  {
    id: 1009,
    regionId: 10,
    name_uz: 'MIROBOD TUMANI',
    name_ru: 'МИРОБОД ТУМАНИ',
    name_en: 'MIROBOD DISTRICT',
  },
  {
    id: 1010,
    regionId: 10,
    name_uz: 'YUNUSOBOD TUMANI',
    name_ru: 'ЮНУСОБОД ТУМАНИ',
    name_en: 'YUNUSABAD DISTRICT',
  },
  {
    id: 1011,
    regionId: 10,
    name_uz: 'BEKTEMIR TUMANI',
    name_ru: 'БЕКТЕМИР ТУМАНИ',
    name_en: 'BEKTEMIR DISTRICT',
  },
  {
    id: 1012,
    regionId: 10,
    name_uz: 'OLMAZOR TUMANI',
    name_ru: 'ОЛМАЗОР ТУМАНИ',
    name_en: 'OLMAZAR DISTRICT',
  },
  {
    id: 1101,
    regionId: 11,
    name_uz: 'YANGIYUL TUMANI',
    name_ru: 'ЯНГИЙУЛ ТУМАНИ',
    name_en: 'YANGIYUL DISTRICT',
  },
  {
    id: 1102,
    regionId: 11,
    name_uz: 'ZANGIOTA TUMANI',
    name_ru: 'ЗАНГИОТА ТУМАНИ',
    name_en: 'ZANGIOTA DISTRICT',
  },
  {
    id: 1103,
    regionId: 11,
    name_uz: 'PISKENT TUMANI',
    name_ru: 'ПИСКЕНТ ТУМАНИ',
    name_en: 'PISKENT DISTRICT',
  },
  {
    id: 1104,
    regionId: 11,
    name_uz: 'PARKENT TUMANI',
    name_ru: 'ПАРКЕНТ ТУМАНИ',
    name_en: 'PARKENT DISTRICT',
  },
  {
    id: 1105,
    regionId: 11,
    name_uz: "O'RTACHIRCHIQ TUMANI",
    name_ru: 'ЎРТАЧИРЧИҚ ТУМАНИ',
    name_en: 'ORTACHIRCHIQ DISTRICT',
  },
  {
    id: 1106,
    regionId: 11,
    name_uz: "OQQO'RG'ON TUMANI",
    name_ru: 'ОҚҚЎРҒОН ТУМАНИ',
    name_en: 'OKKURGAN DISTRICT',
  },
  {
    id: 1107,
    regionId: 11,
    name_uz: 'QUYICHIRCHIQ TUMANI',
    name_ru: 'ҚУЙИЧИРЧИҚ ТУМАНИ',
    name_en: 'QUYICHIRCHIQ DISTRICT',
  },
  {
    id: 1108,
    regionId: 11,
    name_uz: 'QIBRAY TUMANI',
    name_ru: 'ҚИБРАЙ ТУМАНИ',
    name_en: 'QIBRAY DISTRICT',
  },
  {
    id: 1109,
    regionId: 11,
    name_uz: 'TOSHKENT TUMANI',
    name_ru: 'ТОШКЕНТ ТУМАНИ',
    name_en: 'TASHKENT DISTRICT',
  },
  {
    id: 1110,
    regionId: 11,
    name_uz: 'OXANGORON TUMANI',
    name_ru: 'ОХАНГОРОН ТУМАНИ',
    name_en: 'OHANGARON DISTRICT',
  },
  {
    id: 1111,
    regionId: 11,
    name_uz: 'BEKOBOD TUMANI',
    name_ru: 'БЕКОБОД ТУМАНИ',
    name_en: 'BEKABAD DISTRICT',
  },
  {
    id: 1112,
    regionId: 11,
    name_uz: "BO'STONLIQ TUMANI",
    name_ru: 'БЎСТОНЛИҚ ТУМАНИ',
    name_en: 'BUSTONLIQ DISTRICT',
  },
  {
    id: 1113,
    regionId: 11,
    name_uz: "BO'KA TUMANI",
    name_ru: 'БЎКА ТУМАНИ',
    name_en: 'BUKA DISTRICT',
  },
  {
    id: 1114,
    regionId: 11,
    name_uz: 'YUQORICHIRCHIQ TUMANI',
    name_ru: 'ЮҚОРИЧИРЧИҚ ТУМАНИ',
    name_en: 'YUKORICHIRCHIQ DISTRICT',
  },
  {
    id: 1115,
    regionId: 11,
    name_uz: 'CHINOZ TUMANI',
    name_ru: 'ЧИНОЗ ТУМАНИ',
    name_en: 'CHINOZ DISTRICT',
  },
  {
    id: 1116,
    regionId: 11,
    name_uz: 'ANGREN SHAHRI',
    name_ru: 'АНГРЕН ШАҲРИ',
    name_en: 'ANGREN CITY',
  },
  {
    id: 1117,
    regionId: 11,
    name_uz: 'BEKOBOD SHAHRI',
    name_ru: 'БЕКОБОД ШАҲРИ',
    name_en: 'BEKABAD CITY',
  },
  {
    id: 1118,
    regionId: 11,
    name_uz: 'OLMALIK SHAHRI',
    name_ru: 'ОЛМАЛИК ШАҲРИ',
    name_en: 'OLMALIK CITY',
  },
  {
    id: 1119,
    regionId: 11,
    name_uz: 'OXANGORON SHAHRI',
    name_ru: 'ОХАНГОРОН ШАҲРИ',
    name_en: 'OHANGARON CITY',
  },
  {
    id: 1120,
    regionId: 11,
    name_uz: 'CHIRCHIQ SHAHRI',
    name_ru: 'ЧИРЧИҚ ШАҲРИ',
    name_en: 'CHIRCHIQ CITY',
  },
  {
    id: 1121,
    regionId: 11,
    name_uz: 'YANGIOBOD SHAHRI',
    name_ru: 'ЯНГИОБОД ШАҲРИ',
    name_en: 'YANGIOBAD CITY',
  },
  {
    id: 1122,
    regionId: 11,
    name_uz: "YANGIYO'L SHAHRI",
    name_ru: 'ЯНГИЙЎЛ ШАҲРИ',
    name_en: 'YANGIYUL CITY',
  },
  {
    id: 1201,
    regionId: 12,
    name_uz: 'SAYXUNOBOD TUMANI',
    name_ru: 'САЙХУНОБОД ТУМАНИ',
    name_en: 'SAYXUNOBOD DISTRICT',
  },
  {
    id: 1202,
    regionId: 12,
    name_uz: 'GULISTON TUMANI',
    name_ru: 'ГУЛИСТОН ТУМАНИ',
    name_en: 'GULISTON DISTRICT',
  },
  {
    id: 1203,
    regionId: 12,
    name_uz: 'BOYOVUT TUMANI',
    name_ru: 'БОЁВУТ ТУМАНИ',
    name_en: 'BOYOVUT DISTRICT',
  },
  {
    id: 1204,
    regionId: 12,
    name_uz: 'MEXNATOBOD TUMANI',
    name_ru: 'МЕХНАТОБОД ТУМАНИ',
    name_en: 'MEXNATOBOD DISTRICT',
  },
  {
    id: 1205,
    regionId: 12,
    name_uz: 'XOVOS TUMANI',
    name_ru: 'ХОВОС ТУМАНИ',
    name_en: 'XOVOS DISTRICT',
  },
  {
    id: 1206,
    regionId: 12,
    name_uz: 'MIRZAOBOD TUMANI',
    name_ru: 'МИРЗАОБОД ТУМАНИ',
    name_en: 'MIRZAOBOD DISTRICT',
  },
  {
    id: 1207,
    regionId: 12,
    name_uz: 'OQOLTIN TUMANI',
    name_ru: 'ОҚОЛТИН ТУМАНИ',
    name_en: 'OQOLTIN DISTRICT',
  },
  {
    id: 1208,
    regionId: 12,
    name_uz: 'SH.RASHIDOV TUMANI',
    name_ru: 'Ш.РАШИДОВ ТУМАНИ',
    name_en: 'SH.RASHIDOV DISTRICT',
  },
  {
    id: 1209,
    regionId: 12,
    name_uz: 'SIRDARYO TUMANI',
    name_ru: 'СИРДАРЁ ТУМАНИ',
    name_en: 'SIRDARYO DISTRICT',
  },
  {
    id: 1210,
    regionId: 12,
    name_uz: 'GULISTON SHAHRI',
    name_ru: 'ГУЛИСТОН ШАҲРИ',
    name_en: 'GULISTON CITY',
  },
  {
    id: 1211,
    regionId: 12,
    name_uz: 'SIRDARYO SHAHRI',
    name_ru: 'СИРДАРЁ ШАҲРИ',
    name_en: 'SIRDARYO CITY',
  },
  {
    id: 1212,
    regionId: 12,
    name_uz: 'SHIRIN SHAHRI',
    name_ru: 'ШИРИН ШАҲРИ',
    name_en: 'SHIRIN CITY',
  },
  {
    id: 1213,
    regionId: 12,
    name_uz: 'YANGIER SHAHRI',
    name_ru: 'ЯНГИЕР ШАҲРИ',
    name_en: 'YANGIER CITY',
  },
  {
    id: 1214,
    regionId: 12,
    name_uz: 'BAXT SHAHRI',
    name_ru: 'БАХТ ШАҲРИ',
    name_en: 'BAXT CITY',
  },
  {
    id: 1215,
    regionId: 12,
    name_uz: 'SARDOBA TUMANI',
    name_ru: 'САРДОБА ТУМАНИ',
    name_en: 'SARDOBA DISTRICT',
  },
  {
    id: 1301,
    regionId: 13,
    name_uz: 'ZARBDOR TUMANI',
    name_ru: 'ЗАРБДОР ТУМАНИ',
    name_en: 'ZARBDOR DISTRICT',
  },
  {
    id: 1302,
    regionId: 13,
    name_uz: "DO'STLIK TUMANI",
    name_ru: 'ДЎСТЛИК ТУМАНИ',
    name_en: 'DOSTLIK DISTRICT',
  },
  {
    id: 1304,
    regionId: 13,
    name_uz: 'FORISH TUMANI',
    name_ru: 'ФОРИШ ТУМАНИ',
    name_en: 'FORISH DISTRICT',
  },
  {
    id: 1305,
    regionId: 13,
    name_uz: 'SHAROF RASHIDOV TUMANI',
    name_ru: 'ШАРОФ РАШИДОВ ТУМАНИ',
    name_en: 'SHAROF RASHIDOV DISTRICT',
  },
  {
    id: 1306,
    regionId: 13,
    name_uz: "G'ALLAOROL TUMANI",
    name_ru: 'ҒАЛЛАОРОЛ ТУМАНИ',
    name_en: "G'ALLAOROL DISTRICT",
  },
  {
    id: 1307,
    regionId: 13,
    name_uz: 'BAXMAL TUMANI',
    name_ru: 'БАХМАЛ ТУМАНИ',
    name_en: 'BAXMAL DISTRICT',
  },
  {
    id: 1308,
    regionId: 13,
    name_uz: 'PAXTAKOR TUMANI',
    name_ru: 'ПАХТАКОР ТУМАНИ',
    name_en: 'PAXTAKOR DISTRICT',
  },
  {
    id: 1309,
    regionId: 13,
    name_uz: 'ZAFAROBOD TUMANI',
    name_ru: 'ЗАФАРОБОД ТУМАНИ',
    name_en: 'ZAFAROBOD DISTRICT',
  },
  {
    id: 1310,
    regionId: 13,
    name_uz: 'ARNASOY TUMANI',
    name_ru: 'АРНАСОЙ ТУМАНИ',
    name_en: 'ARNASOY DISTRICT',
  },
  {
    id: 1311,
    regionId: 13,
    name_uz: 'ZOMIN TUMANI',
    name_ru: 'ЗОМИН ТУМАНИ',
    name_en: 'ZOMIN DISTRICT',
  },
  {
    id: 1312,
    regionId: 13,
    name_uz: "MIRZACHO'L TUMANI",
    name_ru: 'МИРЗАЧЎЛ ТУМАНИ',
    name_en: "MIRZACHO'L DISTRICT",
  },
  {
    id: 1313,
    regionId: 13,
    name_uz: 'YANGIOBOD TUMANI',
    name_ru: 'ЯНГИОБОД ТУМАНИ',
    name_en: 'YANGIOBAD DISTRICT',
  },
  {
    id: 1314,
    regionId: 13,
    name_uz: 'JIZZAX SHAHRI',
    name_ru: 'ЖИЗЗАХ ШАҲРИ',
    name_en: 'JIZZAX CITY',
  },
  {
    id: 1401,
    regionId: 14,
    name_uz: 'NARPAY TUMANI',
    name_ru: 'НАРПАЙ ТУМАНИ',
    name_en: 'NARPAY DISTRICT',
  },
  {
    id: 1402,
    regionId: 14,
    name_uz: 'NUROBOD TUMANI',
    name_ru: 'НУРОБОД ТУМАНИ',
    name_en: 'NUROBOD DISTRICT',
  },
  {
    id: 1403,
    regionId: 14,
    name_uz: 'JOMBOY TUMANI',
    name_ru: 'ЖОМБОЙ ТУМАНИ',
    name_en: 'JOMBOY DISTRICT',
  },
  {
    id: 1404,
    regionId: 14,
    name_uz: 'URGUT TUMANI',
    name_ru: 'УРГУТ ТУМАНИ',
    name_en: 'URGUT DISTRICT',
  },
  {
    id: 1405,
    regionId: 14,
    name_uz: 'PAXTACHI TUMANI',
    name_ru: 'ПАХТАЧИ ТУМАНИ',
    name_en: 'PAXTACHI DISTRICT',
  },
  {
    id: 1406,
    regionId: 14,
    name_uz: 'KATTAQORGAN TUMANI',
    name_ru: 'КАТТАҚЎРҒОН ТУМАНИ',
    name_en: 'KATTAQORGAN DISTRICT',
  },
  {
    id: 1407,
    regionId: 14,
    name_uz: 'OQDARYO TUMANI',
    name_ru: 'ОҚДАРЁ ТУМАНИ',
    name_en: 'OQDARYO DISTRICT',
  },
  {
    id: 1408,
    regionId: 14,
    name_uz: 'ISHTIXON TUMANI',
    name_ru: 'ИШТИХОН ТУМАНИ',
    name_en: 'ISHTIXON DISTRICT',
  },
  {
    id: 1409,
    regionId: 14,
    name_uz: "PASTDARG'OM TUMANI",
    name_ru: 'ПАСТДАРҒОМ ТУМАНИ',
    name_en: 'PASTDARGOM DISTRICT',
  },
  {
    id: 1410,
    regionId: 14,
    name_uz: 'TAYLOQ TUMANI',
    name_ru: 'ТАЙЛОҚ ТУМАНИ',
    name_en: 'TAYLUK DISTRICT',
  },
  {
    id: 1411,
    regionId: 14,
    name_uz: "BULUNG'UR TUMANI",
    name_ru: 'БУЛУНҒУР ТУМАНИ',
    name_en: "BULUNG'UR DISTRICT",
  },
  {
    id: 1412,
    regionId: 14,
    name_uz: "GO'ZALKENT TUMANI",
    name_ru: 'ГЎЗАЛКЕНТ ТУМАНИ',
    name_en: "GO'ZALKENT DISTRICT",
  },
  {
    id: 1413,
    regionId: 14,
    name_uz: 'SAMARQAND TUMANI',
    name_ru: 'САМАРҚАНД ТУМАНИ',
    name_en: 'SAMARKAND DISTRICT',
  },
  {
    id: 1414,
    regionId: 14,
    name_uz: "QO'SHRABOD TUMANI",
    name_ru: 'ҚЎШРАБОД ТУМАНИ',
    name_en: "QO'SHRABOD DISTRICT",
  },
  {
    id: 1415,
    regionId: 14,
    name_uz: 'PAYARIQ TUMANI',
    name_ru: 'ПАЙАРИҚ ТУМАНИ',
    name_en: 'PAYARIQ DISTRICT',
  },
  {
    id: 1416,
    regionId: 14,
    name_uz: 'CHELAK TUMANI',
    name_ru: 'ЧЕЛАК ТУМАНИ',
    name_en: 'CHELAK DISTRICT',
  },
  {
    id: 1417,
    regionId: 14,
    name_uz: 'SAMARQAND SHAHRI',
    name_ru: 'САМАРҚАНД ШАҲРИ',
    name_en: 'SAMARKAND CITY',
  },
  {
    id: 1418,
    regionId: 14,
    name_uz: "BOG'ISHAMOL TUMANI",
    name_ru: 'БОҒИШАМОЛ ТУМАНИ',
    name_en: "BOG'ISHAMOL DISTRICT",
  },
  {
    id: 1419,
    regionId: 14,
    name_uz: "TEMIRYO'L TUMANI",
    name_ru: 'ТЕМИРЙЎЛ ТУМАНИ',
    name_en: "TEMIRYO'L DISTRICT",
  },
  {
    id: 1420,
    regionId: 14,
    name_uz: 'OQTOSH SHAHRI',
    name_ru: 'ОҚТОШ ШАҲРИ',
    name_en: 'OQTOSH CITY',
  },
  {
    id: 1421,
    regionId: 14,
    name_uz: "KATTAQO'RG'ON SHAHRI",
    name_ru: 'КАТТАҚЎРҒОН ШАҲРИ',
    name_en: "KATTAQO'RG'ON CITY",
  },
  {
    id: 1422,
    regionId: 14,
    name_uz: 'URGUT SHAHRI',
    name_ru: 'УРГУТ ШАҲРИ',
    name_en: 'URGUT CITY',
  },
  {
    id: 1423,
    regionId: 14,
    name_uz: 'SIYOB TUMANI',
    name_ru: 'СИЁБ ТУМАНИ',
    name_en: 'SIYOB DISTRICT',
  },
  {
    id: 1501,
    regionId: 15,
    name_uz: 'KIRGULI TUMANI',
    name_ru: 'КИРГУЛИ ТУМАНИ',
    name_en: 'KIRGULI DISTRICT',
  },
  {
    id: 1502,
    regionId: 15,
    name_uz: "FARG'ONA TUMANI",
    name_ru: 'ФАРҒОНА ТУМАНИ',
    name_en: 'FARGHONA DISTRICT',
  },
  {
    id: 1503,
    regionId: 15,
    name_uz: 'QUVA TUMANI',
    name_ru: 'ҚУВА ТУМАНИ',
    name_en: 'QUVA DISTRICT',
  },
  {
    id: 1504,
    regionId: 15,
    name_uz: 'TOSHLOQ TUMANI',
    name_ru: 'ТОШЛОҚ ТУМАНИ',
    name_en: 'TOSHLOQ DISTRICT',
  },
  {
    id: 1505,
    regionId: 15,
    name_uz: 'OXUNBOBOEV TUMANI',
    name_ru: 'ОХУНБОБОЕВ ТУМАНИ',
    name_en: 'OXUNBOBOEV DISTRICT',
  },
  {
    id: 1506,
    regionId: 15,
    name_uz: 'YOZYOVON TUMANI',
    name_ru: 'ЁЗЁВОН ТУМАНИ',
    name_en: 'YOZYOVON DISTRICT',
  },
  {
    id: 1507,
    regionId: 15,
    name_uz: 'OLTIARIQ TUMANI',
    name_ru: 'ОЛТИАРИҚ ТУМАНИ',
    name_en: 'OLTIARIQ DISTRICT',
  },
  {
    id: 1508,
    regionId: 15,
    name_uz: "BOG'DOD TUMANI",
    name_ru: 'БОҒДОД ТУМАНИ',
    name_en: "BOG'DOD DISTRICT",
  },
  {
    id: 1509,
    regionId: 15,
    name_uz: 'BUVAYDA TUMANI',
    name_ru: 'БУВАЙДА ТУМАНИ',
    name_en: 'BUVAYDA DISTRICT',
  },
  {
    id: 1510,
    regionId: 15,
    name_uz: "UCHKO'PRIK TUMANI",
    name_ru: 'УЧКЎПРИК ТУМАНИ',
    name_en: "UCHKO'PRIK DISTRICT",
  },
  {
    id: 1511,
    regionId: 15,
    name_uz: 'RISHTON TUMANI',
    name_ru: 'РИШТОН ТУМАНИ',
    name_en: 'RISHTON DISTRICT',
  },
  {
    id: 1512,
    regionId: 15,
    name_uz: 'DANGARA TUMANI',
    name_ru: 'ДАНГАРА ТУМАНИ',
    name_en: 'DANGARA DISTRICT',
  },
  {
    id: 1513,
    regionId: 15,
    name_uz: 'FURQAT TUMANI',
    name_ru: 'ФУРҚАТ ТУМАНИ',
    name_en: 'FURQAT DISTRICT',
  },
  {
    id: 1514,
    regionId: 15,
    name_uz: "O'ZBEKISTON TUMANI",
    name_ru: 'ЎЗБЕКИСТОН ТУМАНИ',
    name_en: "O'ZBEKISTON DISTRICT",
  },
  {
    id: 1515,
    regionId: 15,
    name_uz: 'BESHARIQ TUMANI',
    name_ru: 'БЕШАРИҚ ТУМАНИ',
    name_en: 'BESHARIQ DISTRICT',
  },
  {
    id: 1516,
    regionId: 15,
    name_uz: "SO'X TUMANI",
    name_ru: 'СЎХ ТУМАНИ',
    name_en: "SO'X DISTRICT",
  },
  {
    id: 1517,
    regionId: 15,
    name_uz: 'QUVASOY SHAHRI',
    name_ru: 'ҚУВАСОЙ ШАҲРИ',
    name_en: 'QUVASOY CITY',
  },
  {
    id: 1518,
    regionId: 15,
    name_uz: 'QUVA SHAHRI',
    name_ru: 'ҚУВА ШАҲРИ',
    name_en: 'QUVA CITY',
  },
  {
    id: 1519,
    regionId: 15,
    name_uz: "QO'QON SHAHRI",
    name_ru: 'ҚЎҚОН ШАҲРИ',
    name_en: "QO'QON CITY",
  },
  {
    id: 1520,
    regionId: 15,
    name_uz: "MARG'ILON SHAHRI",
    name_ru: 'МАРҒИЛОН ШАҲРИ',
    name_en: "MARG'ILON CITY",
  },
  {
    id: 1521,
    regionId: 15,
    name_uz: "FARG'ONA SHAHRI",
    name_ru: 'ФАРҒОНА ШАҲРИ',
    name_en: 'FARGHONA CITY',
  },
  {
    id: 1522,
    regionId: 15,
    name_uz: 'KIRGULI SHAHRI',
    name_ru: 'КИРГУЛИ ШАҲРИ',
    name_en: 'KIRGULI CITY',
  },
  {
    id: 1601,
    regionId: 16,
    name_uz: 'DAVLATOBOD TUMANI',
    name_ru: 'ДАВЛАТОБОД ТУМАНИ',
    name_en: 'DAVLATOBOD DISTRICT',
  },
  {
    id: 1602,
    regionId: 16,
    name_uz: 'MINGBULOQ TUMANI',
    name_ru: 'МИНГБУЛОҚ ТУМАНИ',
    name_en: 'MINGBULOT DISTRICT',
  },
  {
    id: 1603,
    regionId: 16,
    name_uz: 'NAMANGAN TUMANI',
    name_ru: 'НАМАНГАН ТУМАНИ',
    name_en: 'NAMANGAN DISTRICT',
  },
  {
    id: 1604,
    regionId: 16,
    name_uz: 'NORIN TUMANI',
    name_ru: 'НОРИН ТУМАНИ',
    name_en: 'NORIN DISTRICT',
  },
  {
    id: 1605,
    regionId: 16,
    name_uz: 'UYCHI TUMANI',
    name_ru: 'УЙЧИ ТУМАНИ',
    name_en: 'UYCHI DISTRICT',
  },
  {
    id: 1606,
    regionId: 16,
    name_uz: "UCHQO'RG'ON TUMANI",
    name_ru: 'УЧҚЎРҒОН ТУМАНИ',
    name_en: "UCHQO'RG'ON DISTRICT",
  },
  {
    id: 1607,
    regionId: 16,
    name_uz: 'CHORTOQ TUMANI',
    name_ru: 'ЧОРТОҚ ТУМАНИ',
    name_en: 'CHORTOQ DISTRICT',
  },
  {
    id: 1608,
    regionId: 16,
    name_uz: "YANGIQO'RG'ON TUMANI",
    name_ru: 'ЯНГИҚЎРҒОН ТУМАНИ',
    name_en: 'YANGIOBAD DISTRICT',
  },
  {
    id: 1609,
    regionId: 16,
    name_uz: 'KOSONSOY TUMANI',
    name_ru: 'КОСОНСОЙ ТУМАНИ',
    name_en: 'KOSONSOY DISTRICT',
  },
  {
    id: 1610,
    regionId: 16,
    name_uz: 'CHUST TUMANI',
    name_ru: 'ЧУСТ ТУМАНИ',
    name_en: 'CHUST DISTRICT',
  },
  {
    id: 1611,
    regionId: 16,
    name_uz: 'POP TUMANI',
    name_ru: 'ПОП ТУМАНИ',
    name_en: 'POP DISTRICT',
  },
  {
    id: 1612,
    regionId: 16,
    name_uz: "TO'RAQO'RG'ON TUMANI",
    name_ru: 'ТЎРАҚЎРҒОН ТУМАНИ',
    name_en: "TO'RAQO'RG'ON DISTRICT",
  },
  {
    id: 1613,
    regionId: 16,
    name_uz: 'NAMANGAN SHAHRI',
    name_ru: 'НАМАНГАН ШАҲРИ',
    name_en: 'NAMANGAN CITY',
  },
  {
    id: 1614,
    regionId: 16,
    name_uz: 'KOSONSOY SHAHRI',
    name_ru: 'КОСОНСОЙ ШАҲРИ',
    name_en: 'KOSONSOY CITY',
  },
  {
    id: 1615,
    regionId: 16,
    name_uz: "UCHQO'RG'ON SHAHRI",
    name_ru: 'УЧҚЎРҒОН ШАҲРИ',
    name_en: "UCHQO'RG'ON CITY",
  },
  {
    id: 1616,
    regionId: 16,
    name_uz: 'CHORTOQ SHAHRI',
    name_ru: 'ЧОРТОҚ ШАҲРИ',
    name_en: 'CHORTOQ CITY',
  },
  {
    id: 1617,
    regionId: 16,
    name_uz: 'CHUST SHAHRI',
    name_ru: 'ЧУСТ ШАҲРИ',
    name_en: 'CHUST CITY',
  },
  {
    id: 1618,
    regionId: 16,
    name_uz: 'XAQQULOBOD SHAHRI',
    name_ru: 'ХАҚҚУЛОБОД ШАҲРИ',
    name_en: 'HAKKULOBOOD CITY',
  },
  {
    id: 1701,
    regionId: 17,
    name_uz: 'ANDIJON TUMANI',
    name_ru: 'АНДИЖОН ТУМАНИ',
    name_en: 'ANDIJON DISTRICT',
  },
  {
    id: 1702,
    regionId: 17,
    name_uz: "OLTINKO'L TUMAN",
    name_ru: 'ОЛТИНКЎЛ ТУМАН',
    name_en: 'OLTINKOL DISTRICT',
  },
  {
    id: 1703,
    regionId: 17,
    name_uz: 'ASAKA TUMAN',
    name_ru: 'АСАКА ТУМАН',
    name_en: 'ASAKA DISTRICT',
  },
  {
    id: 1704,
    regionId: 17,
    name_uz: 'BALIQCHI TUMAN',
    name_ru: 'БАЛИҚЧИ ТУМАН',
    name_en: 'BALIQCHI DISTRICT',
  },
  {
    id: 1705,
    regionId: 17,
    name_uz: "BO'Z TUMANI",
    name_ru: 'БЎЗ ТУМАНИ',
    name_en: "BO'Z DISTRICT",
  },
  {
    id: 1706,
    regionId: 17,
    name_uz: "ULUG'NOR TUMANI",
    name_ru: 'УЛУҒНОР ТУМАНИ',
    name_en: "ULUG'NOR DISTRICT",
  },
  {
    id: 1707,
    regionId: 17,
    name_uz: 'SHAXRIXON TUMANI',
    name_ru: 'ШАХРИХОН ТУМАНИ',
    name_en: 'SHAXRIXON DISTRICT',
  },
  {
    id: 1708,
    regionId: 17,
    name_uz: "QO'RG'ONTEPA TUMANI",
    name_ru: 'ҚЎРҒОНТЕПА ТУМАНИ',
    name_en: "QO'RG'ONTEPA DISTRICT",
  },
  {
    id: 1709,
    regionId: 17,
    name_uz: 'JALOLQUDUQ TUMANI',
    name_ru: 'ЖАЛОЛҚУДУҚ ТУМАНИ',
    name_en: 'JALOLQUDUQ DISTRICT',
  },
  {
    id: 1710,
    regionId: 17,
    name_uz: "XO'JAOBOD TUMANI",
    name_ru: 'ХЎЖАОБОД ТУМАНИ',
    name_en: "XO'JAOBOD DISTRICT",
  },
  {
    id: 1711,
    regionId: 17,
    name_uz: 'MARXAMAT TUMANI',
    name_ru: 'МАРХАМАТ ТУМАНИ',
    name_en: 'MARXAMAT DISTRICT',
  },
  {
    id: 1712,
    regionId: 17,
    name_uz: 'IZBOSKAN TUMANI',
    name_ru: 'ИЗБОСКАН ТУМАНИ',
    name_en: 'IZBOSKAN DISTRICT',
  },
  {
    id: 1713,
    regionId: 17,
    name_uz: 'BULOQBOSHI TUMANI',
    name_ru: 'БУЛОҚБОШИ ТУМАНИ',
    name_en: 'BULOKBOSHI DISTRICT',
  },
  {
    id: 1714,
    regionId: 17,
    name_uz: 'PAXTAOBOD TUMANI',
    name_ru: 'ПАХТАОБОД ТУМАНИ',
    name_en: 'PAXTAOBOD DISTRICT',
  },
  {
    id: 1715,
    regionId: 17,
    name_uz: 'ANDIJON SHAHRI',
    name_ru: 'АНДИЖОН ШАҲРИ',
    name_en: 'ANDIJON CITY',
  },
  {
    id: 1716,
    regionId: 17,
    name_uz: 'ASAKA SHAHRI',
    name_ru: 'АСАКА ШАҲРИ',
    name_en: 'ASAKA CITY',
  },
  {
    id: 1717,
    regionId: 17,
    name_uz: 'XONOBOD SHAHRI',
    name_ru: 'ХОНОБОД ШАҲРИ',
    name_en: 'XONOBOD CITY',
  },
  {
    id: 1718,
    regionId: 17,
    name_uz: 'SHAHRIXON SHAHRI',
    name_ru: 'ШАҲРИХОН ШАҲРИ',
    name_en: 'SHAXRIXON CITY',
  },
  {
    id: 1719,
    regionId: 17,
    name_uz: 'QORASUV SHAHRI',
    name_ru: 'ҚОРАСУВ ШАҲРИ',
    name_en: 'QORASUV CITY',
  },
  {
    id: 1801,
    regionId: 18,
    name_uz: 'CHIROQCHI TUMANI',
    name_ru: 'ЧИРОҚЧИ ТУМАНИ',
    name_en: 'CHIROQCHI DISTRICT',
  },
  {
    id: 1802,
    regionId: 18,
    name_uz: 'KOSON TUMANI',
    name_ru: 'КОСОН ТУМАНИ',
    name_en: 'KOSON DISTRICT',
  },
  {
    id: 1803,
    regionId: 18,
    name_uz: 'SHAXRISABZ TUMANI',
    name_ru: 'ШАХРИСАБЗ ТУМАНИ',
    name_en: 'SHAHRISABZ DISTRICT',
  },
  {
    id: 1804,
    regionId: 18,
    name_uz: 'DEHQONOBOD TUMANI',
    name_ru: 'ДЕҲҚОНОБОД ТУМАНИ',
    name_en: 'DEHQONOBOD DISTRICT',
  },
  {
    id: 1805,
    regionId: 18,
    name_uz: 'QAMASHI TUMANI',
    name_ru: 'ҚАМАШИ ТУМАНИ',
    name_en: 'QAMASHI DISTRICT',
  },
  {
    id: 1806,
    regionId: 18,
    name_uz: "YAKKABOG' TUMANI",
    name_ru: 'ЯККАБОҒ ТУМАНИ',
    name_en: "YAKKABOG' DISTRICT",
  },
  {
    id: 1807,
    regionId: 18,
    name_uz: 'BAXORISTON TUMANI',
    name_ru: 'БАХОРИСТОН ТУМАНИ',
    name_en: 'BAHORISTON DISTRICT',
  },
  {
    id: 1808,
    regionId: 18,
    name_uz: "G'UZOR TUMANI",
    name_ru: 'ҒУЗОР ТУМАНИ',
    name_en: 'GUZOR DISTRICT',
  },
  {
    id: 1809,
    regionId: 18,
    name_uz: 'QARSHI TUMANI',
    name_ru: 'ҚАРШИ ТУМАНИ',
    name_en: 'QARSHI DISTRICT',
  },
  {
    id: 1810,
    regionId: 18,
    name_uz: 'NISHON TUMANI',
    name_ru: 'НИШОН ТУМАНИ',
    name_en: 'NISHON DISTRICT',
  },
  {
    id: 1811,
    regionId: 18,
    name_uz: 'KITOB TUMANI',
    name_ru: 'КИТОБ ТУМАНИ',
    name_en: 'KITOB DISTRICT',
  },
  {
    id: 1812,
    regionId: 18,
    name_uz: 'KASBI TUMANI',
    name_ru: 'КАСБИ ТУМАНИ',
    name_en: 'KASBI DISTRICT',
  },
  {
    id: 1813,
    regionId: 18,
    name_uz: 'MUBORAK TUMANI',
    name_ru: 'МУБОРАК ТУМАНИ',
    name_en: 'MUBORAK DISTRICT',
  },
  {
    id: 1814,
    regionId: 18,
    name_uz: 'MIRISHKOR TUMANI',
    name_ru: 'МИРИШКОР ТУМАНИ',
    name_en: 'MIRISHKOR DISTRICT',
  },
  {
    id: 1815,
    regionId: 18,
    name_uz: 'QARSHI SHAHRI',
    name_ru: 'ҚАРШИ ШАҲРИ',
    name_en: 'QARSHI CITY',
  },
  {
    id: 1816,
    regionId: 18,
    name_uz: 'SHAHRISABZ SHAHRI',
    name_ru: 'ШАҲРИСАБЗ ШАҲРИ',
    name_en: 'SHAHRISABZ CITY',
  },
  {
    id: 1901,
    regionId: 19,
    name_uz: 'TERMIZ TUMANI',
    name_ru: 'ТЕРМИЗ ТУМАНИ',
    name_en: 'TERMIZ DISTRICT',
  },
  {
    id: 1902,
    regionId: 19,
    name_uz: 'BOYSUN TUMANI',
    name_ru: 'БОЙСУН ТУМАНИ',
    name_en: 'BOYSUN DISTRICT',
  },
  {
    id: 1903,
    regionId: 19,
    name_uz: 'MUZRABOT TUMANI',
    name_ru: 'МУЗРАБОТ ТУМАНИ',
    name_en: 'MUZRABOT DISTRICT',
  },
  {
    id: 1904,
    regionId: 19,
    name_uz: 'SARIOSIYO TUMANI',
    name_ru: 'САРИОСИЁ ТУМАНИ',
    name_en: 'SARIOSIYO DISTRICT',
  },
  {
    id: 1905,
    regionId: 19,
    name_uz: "SHARG'UN TUMANI",
    name_ru: 'ШАРҒУН ТУМАНИ',
    name_en: 'SHARGUN DISTRICT',
  },
  {
    id: 1906,
    regionId: 19,
    name_uz: "SHO'RCHI TUMANI",
    name_ru: 'ШЎРЧИ ТУМАНИ',
    name_en: 'SHORCHI DISTRICT',
  },
  {
    id: 1907,
    regionId: 19,
    name_uz: 'OLTINSOY TUMANI',
    name_ru: 'ОЛТИНСОЙ ТУМАНИ',
    name_en: 'OLTINSOY DISTRICT',
  },
  {
    id: 1908,
    regionId: 19,
    name_uz: "QUMQO'RG'ON TUMANI",
    name_ru: 'ҚУМҚЎРҒОН ТУМАНИ',
    name_en: 'QUMQORON DISTRICT',
  },
  {
    id: 1909,
    regionId: 19,
    name_uz: "JARQO'RG'ON TUMANI",
    name_ru: 'ЖАРҚЎРҒОН ТУМАНИ',
    name_en: 'JARQORON DISTRICT',
  },
  {
    id: 1910,
    regionId: 19,
    name_uz: 'QIZIRIQ TUMANI',
    name_ru: 'ҚИЗИРИҚ ТУМАНИ',
    name_en: 'QIZIRIQ DISTRICT',
  },
  {
    id: 1911,
    regionId: 19,
    name_uz: 'ANGOR TUMANI',
    name_ru: 'АНГОР ТУМАНИ',
    name_en: 'ANGOR DISTRICT',
  },
  {
    id: 1912,
    regionId: 19,
    name_uz: 'SHEROBOD TUMANI',
    name_ru: 'ШЕРОБОД ТУМАНИ',
    name_en: 'SHEROBOD DISTRICT',
  },
  {
    id: 1913,
    regionId: 19,
    name_uz: 'UZUN TUMANI',
    name_ru: 'УЗУН ТУМАНИ',
    name_en: 'UZUN DISTRICT',
  },
  {
    id: 1914,
    regionId: 19,
    name_uz: 'DENOV TUMANI',
    name_ru: 'ДЕНОВ ТУМАНИ',
    name_en: 'DENOV DISTRICT',
  },
  {
    id: 1915,
    regionId: 19,
    name_uz: 'BANDIXON TUMANI',
    name_ru: 'БАНДИХОН ТУМАНИ',
    name_en: 'BANDIXON DISTRICT',
  },
  {
    id: 1916,
    regionId: 19,
    name_uz: 'TERMIZ SHAHRI',
    name_ru: 'ТЕРМИЗ ШАҲРИ',
    name_en: 'TERMIZ CITY',
  },
  {
    id: 1917,
    regionId: 19,
    name_uz: 'DENOV SHAHRI',
    name_ru: 'ДЕНОВ ШАҲРИ',
    name_en: 'DENOV CITY',
  },
  {
    id: 2001,
    regionId: 20,
    name_uz: 'ROMITON TUMANI',
    name_ru: 'РОМИТОН ТУМАНИ',
    name_en: 'ROMITON DISTRICT',
  },
  {
    id: 2002,
    regionId: 20,
    name_uz: 'VOBKENT TUMANI',
    name_ru: 'ВОБКЕНТ ТУМАНИ',
    name_en: 'VOBKENT DISTRICT',
  },
  {
    id: 2003,
    regionId: 20,
    name_uz: 'PESHKU TUMANI',
    name_ru: 'ПЕШКУ ТУМАНИ',
    name_en: 'PESHKU DISTRICT',
  },
  {
    id: 2004,
    regionId: 20,
    name_uz: 'OLOT TUMANI',
    name_ru: 'ОЛОТ ТУМАНИ',
    name_en: 'OLOT DISTRICT',
  },
  {
    id: 2005,
    regionId: 20,
    name_uz: 'JONDOR TUMANI',
    name_ru: 'ЖОНДОР ТУМАНИ',
    name_en: 'JONDOR DISTRICT',
  },
  {
    id: 2006,
    regionId: 20,
    name_uz: "QORAKO'L TUMANI",
    name_ru: 'ҚОРАКЎЛ ТУМАНИ',
    name_en: 'QORAKOL DISTRICT',
  },
  {
    id: 2007,
    regionId: 20,
    name_uz: 'SHOFIRKON TUMANI',
    name_ru: 'ШОФИРКОН ТУМАНИ',
    name_en: 'SHOFIRKON DISTRICT',
  },
  {
    id: 2008,
    regionId: 20,
    name_uz: 'QOROVULBOZOR TUMANI',
    name_ru: 'ҚОРОВУЛБОЗОР ТУМАНИ',
    name_en: 'QOROVULBOZOR DISTRICT',
  },
  {
    id: 2009,
    regionId: 20,
    name_uz: 'GAZLI SHAHRI',
    name_ru: 'ГАЗЛИ ШАҲРИ',
    name_en: 'GAZLI CITY',
  },
  {
    id: 2010,
    regionId: 20,
    name_uz: 'BUXORO TUMANI',
    name_ru: 'БУХОРО ТУМАНИ',
    name_en: 'BUXORO DISTRICT',
  },
  {
    id: 2011,
    regionId: 20,
    name_uz: 'KOGON TUMANI',
    name_ru: 'КОГОН ТУМАНИ',
    name_en: 'KOGON DISTRICT',
  },
  {
    id: 2012,
    regionId: 20,
    name_uz: "G'IJDUVON TUMANI",
    name_ru: 'ҒИЖДУВОН ТУМАНИ',
    name_en: 'GIJDUVON DISTRICT',
  },
  {
    id: 2013,
    regionId: 20,
    name_uz: 'BUXORO SHAHRI',
    name_ru: 'БУХОРО ШАҲРИ',
    name_en: 'BUXORO CITY',
  },
  {
    id: 2014,
    regionId: 20,
    name_uz: "G'IJDUVON SHAHRI",
    name_ru: 'ҒИЖДУВОН ШАҲРИ',
    name_en: 'GIJDUVON CITY',
  },
  {
    id: 2015,
    regionId: 20,
    name_uz: 'KOGON SHAHRI',
    name_ru: 'КОГОН ШАҲРИ',
    name_en: 'KOGON CITY',
  },
  {
    id: 2016,
    regionId: 20,
    name_uz: "F.XO'JAEV TUMANI",
    name_ru: 'Ф.ХЎЖАЕВ ТУМАНИ',
    name_en: 'F.XOJAEV DISTRICT',
  },
  {
    id: 2017,
    regionId: 20,
    name_uz: "TO'QIMACHI TUMANI",
    name_ru: 'ТЎҚИМАЧИ ТУМАНИ',
    name_en: 'TOQIMACHI DISTRICT',
  },
  {
    id: 2101,
    regionId: 21,
    name_uz: 'UCHQUDUQ TUMANI',
    name_ru: 'УЧҚУДУҚ ТУМАНИ',
    name_en: 'UCHQODUQ DISTRICT',
  },
  {
    id: 2102,
    regionId: 21,
    name_uz: 'KONIMEX TUMANI',
    name_ru: 'КОНИМЕХ ТУМАНИ',
    name_en: 'KONIMEX DISTRICT',
  },
  {
    id: 2104,
    regionId: 21,
    name_uz: 'TOMDI TUMANI',
    name_ru: 'ТОМДИ ТУМАНИ',
    name_en: 'TOMDI DISTRICT',
  },
  {
    id: 2105,
    regionId: 21,
    name_uz: 'NAVBAHOR TUMANI',
    name_ru: 'НАВБАҲОР ТУМАНИ',
    name_en: 'NAVBAHOR DISTRICT',
  },
  {
    id: 2106,
    regionId: 21,
    name_uz: 'NAVOIY TUMANI',
    name_ru: 'НАВОИЙ ТУМАНИ',
    name_en: 'NAVOIY DISTRICT',
  },
  {
    id: 2107,
    regionId: 21,
    name_uz: 'NUROTA TUMANI',
    name_ru: 'НУРОТА ТУМАНИ',
    name_en: 'NUROTA DISTRICT',
  },
  {
    id: 2108,
    regionId: 21,
    name_uz: 'XATIRCHI TUMANI',
    name_ru: 'ХАТИРЧИ ТУМАНИ',
    name_en: 'XATIRCHI DISTRICT',
  },
  {
    id: 2109,
    regionId: 21,
    name_uz: 'QIZILTEPA TUMANI',
    name_ru: 'ҚИЗИЛТЕПА ТУМАНИ',
    name_en: 'QIZILTEPA DISTRICT',
  },
  {
    id: 2110,
    regionId: 21,
    name_uz: 'KARMANA TUMANI',
    name_ru: 'КАРМАНА ТУМАНИ',
    name_en: 'KARMANA DISTRICT',
  },
  {
    id: 2111,
    regionId: 21,
    name_uz: 'NAVOIY SHAHRI',
    name_ru: 'НАВОИЙ ШАҲРИ',
    name_en: 'NAVOIY CITY',
  },
  {
    id: 2112,
    regionId: 21,
    name_uz: 'ZARAFSHON SHAHRI',
    name_ru: 'ЗАРАФШОН ШАҲРИ',
    name_en: 'ZARAFSHON CITY',
  },
  {
    id: 2113,
    regionId: 21,
    name_uz: 'UCHQUDUQ SHAHRI',
    name_ru: 'УЧҚУДУҚ ШАҲРИ',
    name_en: "UCHQO'DUQ CITY",
  },
  {
    id: 2201,
    regionId: 22,
    name_uz: 'XAZORASP TUMANI',
    name_ru: 'ХАЗОРАСП ТУМАНИ',
    name_en: 'HAZORASP DISTRICT',
  },
  {
    id: 2202,
    regionId: 22,
    name_uz: 'YANGIARIQ TUMANI',
    name_ru: 'ЯНГИАРИҚ ТУМАНИ',
    name_en: 'YANGIARIQ DISTRICT',
  },
  {
    id: 2203,
    regionId: 22,
    name_uz: 'GURLAN TUMANI',
    name_ru: 'ГУРЛАН ТУМАНИ',
    name_en: 'GURLAN DISTRICT',
  },
  {
    id: 2204,
    regionId: 22,
    name_uz: 'URGANCH TUMANI',
    name_ru: 'УРГАНЧ ТУМАНИ',
    name_en: 'URGANCH DISTRICT',
  },
  {
    id: 2205,
    regionId: 22,
    name_uz: 'SHOVOT TUMANI',
    name_ru: 'ШОВОТ ТУМАНИ',
    name_en: 'SHOVOT DISTRICT',
  },
  {
    id: 2206,
    regionId: 22,
    name_uz: 'XONQA TUMANI',
    name_ru: 'ХОНҚА ТУМАНИ',
    name_en: 'XONQA DISTRICT',
  },
  {
    id: 2207,
    regionId: 22,
    name_uz: "BOG'OT TUMANI",
    name_ru: 'БОҒОТ ТУМАНИ',
    name_en: 'BOGOT DISTRICT',
  },
  {
    id: 2208,
    regionId: 22,
    name_uz: 'YANGIBOZOR TUMANI',
    name_ru: 'ЯНГИБОЗОР ТУМАНИ',
    name_en: 'YANGIBOZOR DISTRICT',
  },
  {
    id: 2209,
    regionId: 22,
    name_uz: "QO'SHKO'PIR TUMANI",
    name_ru: 'ҚЎШКЎПИР ТУМАНИ',
    name_en: "QO'SHKO'PIR DISTRICT",
  },
  {
    id: 2210,
    regionId: 22,
    name_uz: 'XIVA TUMANI',
    name_ru: 'ХИВА ТУМАНИ',
    name_en: 'XIVA DISTRICT',
  },
  {
    id: 2211,
    regionId: 22,
    name_uz: 'URGANCH SHAHRI',
    name_ru: 'УРГАНЧ ШАҲРИ',
    name_en: 'URGANCH CITY',
  },
  {
    id: 2212,
    regionId: 22,
    name_uz: 'XIVA SHAHRI',
    name_ru: 'ХИВА ШАҲРИ',
    name_en: 'XIVA CITY',
  },
  {
    id: 2213,
    regionId: 22,
    name_uz: 'PITNAK SHAHRI',
    name_ru: 'ПИТНАК ШАҲРИ',
    name_en: 'PITNAK CITY',
  },
  {
    id: 2301,
    regionId: 23,
    name_uz: 'NUKUS TUMANI',
    name_ru: 'НУКУС ТУМАНИ',
    name_en: 'NUKUS DISTRICT',
  },
  {
    id: 2302,
    regionId: 23,
    name_uz: 'KUNGIROT TUMANI',
    name_ru: 'КУНГИРОТ ТУМАНИ',
    name_en: 'KUNGIROT DISTRICT',
  },
  {
    id: 2303,
    regionId: 23,
    name_uz: "MO'YNOQ TUMANI",
    name_ru: 'МЎЙНОҚ ТУМАНИ',
    name_en: "MO'YNOQ DISTRICT",
  },
  {
    id: 2305,
    regionId: 23,
    name_uz: "TO'RTKO'L TUMANI",
    name_ru: 'ТЎРТКЎЛ ТУМАНИ',
    name_en: "TO'RTKO'L DISTRICT",
  },
  {
    id: 2306,
    regionId: 23,
    name_uz: 'ELLIKQALA TUMANI',
    name_ru: 'ЭЛЛИКҚАЛЪА ТУМАНИ',
    name_en: 'ELLIKQALA DISTRICT',
  },
  {
    id: 2307,
    regionId: 23,
    name_uz: 'KEGEYLI TUMANI',
    name_ru: 'КЕГЕЙЛИ ТУМАНИ',
    name_en: 'KEGEYLI DISTRICT',
  },
  {
    id: 2308,
    regionId: 23,
    name_uz: 'AMUDARYO TUMANI',
    name_ru: 'АМУДАРЁ ТУМАНИ',
    name_en: 'AMUDARYO DISTRICT',
  },
  {
    id: 2309,
    regionId: 23,
    name_uz: 'BERUNIY TUMANI',
    name_ru: 'БЕРУНИЙ ТУМАНИ',
    name_en: 'BERUNIY DISTRICT',
  },
  {
    id: 2310,
    regionId: 23,
    name_uz: 'KANLIKOL TUMANI',
    name_ru: 'КАНЛИКОЛ ТУМАНИ',
    name_en: 'KANLIKOL DISTRICT',
  },
  {
    id: 2311,
    regionId: 23,
    name_uz: 'CHIMBOY TUMANI',
    name_ru: 'ЧИМБОЙ ТУМАНИ',
    name_en: 'CHIMBOY DISTRICT',
  },
  {
    id: 2312,
    regionId: 23,
    name_uz: 'SHUMANAY TUMANI',
    name_ru: 'ШУМАНАЙ ТУМАНИ',
    name_en: 'SHUMANAY DISTRICT',
  },
  {
    id: 2313,
    regionId: 23,
    name_uz: "TAXTAKO'PIR TUMANI",
    name_ru: 'ТАХТАКЎПИР ТУМАНИ',
    name_en: "TAHTAKO'PIR DISTRICT",
  },
  {
    id: 2314,
    regionId: 23,
    name_uz: 'XOJELI TUMANI',
    name_ru: 'ХОЖЕЛИ ТУМАНИ',
    name_en: 'XOJELI DISTRICT',
  },
  {
    id: 2315,
    regionId: 23,
    name_uz: 'BOZATAU TUMANI',
    name_ru: 'БОЗАТАУ ТУМАНИ',
    name_en: 'BOZATAU DISTRICT',
  },
  {
    id: 2316,
    regionId: 23,
    name_uz: 'QORAUZOQ TUMANI',
    name_ru: 'ҚОРАУЗОҚ ТУМАНИ',
    name_en: 'QORAUZOQ DISTRICT',
  },
  {
    id: 2317,
    regionId: 23,
    name_uz: 'NUKUS SHAHRI',
    name_ru: 'НУКУС ШАҲРИ',
    name_en: 'NUKUS CITY',
  },
  {
    id: 2318,
    regionId: 23,
    name_uz: 'BERUNIY SHAHRI',
    name_ru: 'БЕРУНИЙ ШАҲРИ',
    name_en: 'BERUNIY CITY',
  },
  {
    id: 2319,
    regionId: 23,
    name_uz: 'KUNGIROT SHAHRI',
    name_ru: 'КУНГИРОТ ШАҲРИ',
    name_en: 'KUNGIROT CITY',
  },
  {
    id: 2320,
    regionId: 23,
    name_uz: 'TAQIYATOSH SHAHRI',
    name_ru: 'ТАҚИЯТОШ ШАҲРИ',
    name_en: 'TAQIYATOSH CITY',
  },
  {
    id: 2321,
    regionId: 23,
    name_uz: "TO'RTKO'L SHAHRI",
    name_ru: 'ТЎРТКЎЛ ШАҲРИ',
    name_en: "TO'RTKO'L CITY",
  },
  {
    id: 2322,
    regionId: 23,
    name_uz: 'XOJELI SHAHRI',
    name_ru: 'ХОЖЕЛИ ШАҲРИ',
    name_en: 'XOJELI CITY',
  },
  {
    id: 2323,
    regionId: 23,
    name_uz: 'CHIMBOY SHAHRI',
    name_ru: 'ЧИМБОЙ ШАҲРИ',
    name_en: 'CHIMBOY CITY',
  },
  {
    id: 2434,
    regionId: 15,
    name_uz: "QO'SHTEPA TUMANI",
    name_ru: 'ҚЎШТЕПА ТУМАНИ',
    name_en: "QO'SHTEPA DISTRICT",
  },
  {
    id: 739001080,
    regionId: 10,
    name_uz: 'YASHNABADSKIY RAYON',
    name_ru: 'ЯШНАБАДСКИЙ РАЙОН',
    name_en: 'YASHNABADSKIY DISTRICT',
  },
  {
    id: 739001100,
    regionId: 13,
    name_uz: 'SHAROF-RASHIDOV TUMANI',
    name_ru: 'ШАРОФ-РАШИДОВ ТУМАНИ',
    name_en: 'SHAROF-RASHIDOV DISTRICT',
  },
  {
    id: 739001120,
    regionId: 11,
    name_uz: 'NURAFSHON SHAHRI',
    name_ru: 'НУРАФШОН ШАҲРИ',
    name_en: 'NURAFSHON CITY',
  },
  {
    id: 739001121,
    regionId: 11,
    name_uz: 'OHANGARON SHAHRI',
    name_ru: 'ОҲАНГАРОН ШАҲРИ',
    name_en: 'OHANGARON CITY',
  },
  {
    id: 739001140,
    regionId: 17,
    name_uz: "BO'STON TUMANI",
    name_ru: 'БЎСТОН ТУМАНИ',
    name_en: 'BOSTON DISTRICT',
  },
  {
    id: 739001141,
    regionId: 22,
    name_uz: 'TUPROQQALA TUMANI',
    name_ru: 'ТУПРОҚҚАЛЪА ТУМАНИ',
    name_en: 'TUPROQQALA DISTRICT',
  },
  {
    id: 739001160,
    regionId: 10,
    name_uz: 'YANGIXAYOT TUMANI',
    name_ru: 'ЯНГИХАЁТ ТУМАНИ',
    name_en: 'YANGIXAYOT DISTRICT',
  },
  {
    id: 739001180,
    regionId: 21,
    name_uz: "G'OZG'ON SHAHRI",
    name_ru: 'ҒОЗҒОН ШАҲРИ',
    name_en: 'GOZGON CITY',
  },
  {
    id: 739001220,
    regionId: 18,
    name_uz: "KO'KDALA TUMANI",
    name_ru: 'КЎКДАЛА ТУМАНИ',
    name_en: 'KOKDALA DISTRICT',
  },
];
